from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'

WINDOW_ICON = FILES_DIR / 'gorilla.png'
# sizing
BIG_FONT = 40
MEDIUM_FONT = 24
SMALL_FONT = 18
DEFAULT_MARGIN = 10
MINIMUM_WIDTH = 500

# colors

PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
